version: "2"
services:

  uwsgi:
    build: ./app
    volumes:
      - ./app:/var/www/
    networks:
      - my_network
    ports:
      - "3031:3031"
    environment:
      TZ: "Asia/Tokyo"

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my_network
    ports:
      - "80:80"
    environment:
      TZ: "Asia/Tokyo"

networks:
  my_network: